"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import FollowBar from "@/components/layout/FollowBar";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";
// import { Toaster } from "react-hot-toast";
import { NextAuthProvider } from "./provider";
import { CustomToast } from "@/components/CustomToast";
const inter = Inter({ subsets: ["latin"] });

// ("use server");
// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {/* <Toaster /> */}
                <CustomToast />
                <NextAuthProvider>
                    {/* <Modal title="What to do next>?" actionLabel="Submit" isOpen /> */}
                    <LoginModal />
                    <RegisterModal />

                    <div className="h-screen bg-black">
                        <div className="container h-full mx-auto xl:px-30 max-w-7xl">
                            <div className="grid grid-cols-4 ml-[-30px] md:ml-[0px] h-full">
                                <Sidebar />
                                <div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800">
                                    {children}
                                </div>
                                <FollowBar />
                            </div>
                        </div>
                    </div>
                </NextAuthProvider>
            </body>
        </html>
    );
}
